config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "pages#home"
  get 'pages/home', to: 'pages#home'
  get '/dashboard', to: 'pages#dashboard'
  get '/listing', to: 'scenes#listing'
  get '/signup', to: 'users#new'
  
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  
  resources :users, except: [:new]
  
  resources :scenes
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/scene.rb
class Scene < ApplicationRecord
  belongs_to :user
  
  validates :title, presence: true
  validates :description, presence: true, length: { minimum: 5, maximum: 500 }
  validates :user_id, presence: true
  
  default_scope -> { order(updated_at: :desc) }
  
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :scenes, dependent: :destroy
  
  before_save { self.email = email.downcase }
  validates :username, presence: true, length: { minimum: 3, maximum: 30},
                    uniqueness: { case_sensitive: false }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: { minimum: 3, maximum: 255},
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 5 }, allow_nil: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  helper_method :current_user, :logged_in?
  
  
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  
  def logged_in?
    !!current_user
  end
  
  def require_user
    if !logged_in?
      flash[:alert] = "You must be logged in to perform that action"
      redirect_to root_path
    end
  end
  
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
  def home
    redirect_to scenes_path if logged_in?
  end
  
  def dashboard
  end
  
end

app/controllers/scenes_controller.rb
class ScenesController < ApplicationController
  before_action :set_scene, only: [:show, :edit, :update, :destroy]
  before_action :require_user, except: [:index, :show]
  before_action :require_same_user, only: [:edit, :update, :destroy]
  
  def index
    @scenes = Scene.paginate(page: params[:page], per_page: 16)
  end
  
  def listing
    @scenes = Scene.all
    redirect_to scenes_path if !logged_in?
  end
  
  def show
  end
  
  def new
    @scene = Scene.new
  end
  
  def create
    @scene = Scene.new(scene_params)
    @scene.user = current_user
    if @scene.save
      flash[:success] = "Scene was created successfully"
      redirect_to scene_path(@scene)
    else
      render 'new'
    end
  end
  
  def edit
  end
  
  def update
    if @scene.update(scene_params)
      flash[:success] = "Scene was successfully updated!"
      redirect_to scene_path(@scene)
    else
      render 'edit'
    end
  end
  
  def destroy
    @scene = Scene.find(params[:id]).destroy
    flash[:success] = "Scene deleted successfully!"
    redirect_to listing_path
  end
  
  private
  
  def require_same_user
    if current_user != @scene.user
      flash[:notice] = "You can only edit or delete your own scenes"
      redirect_to scenes_path
    end
  end
  
  def set_scene
    @scene = Scene.find(params[:id])
  end
  
  def scene_params
    params.require(:scene).permit(:title, :description)
  end
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
    
  end

 def create
  user = User.find_by(email: params[:session][:email].downcase)
  if user && user.authenticate(params[:session][:password])
    session[:user_id] = user.id
    flash[:success] = "You have successfully logged in!"
    redirect_to user
  else
    flash.now[:notice] = "There was something wrong with your login information"
    render 'new'
  end
 end
 
 def destroy
    session[:user_id] = nil
    flash[:success] = "You have logged out!"
    redirect_to scenes_path
 end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :require_same_user, only: [:edit, :update, :destroy]

  def index
    @users = User.paginate(page: params[:page])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "Welcome to Pornoleros, #{@user.username}!"
      redirect_to user_path(@user)
    else
      render 'new'
    end
  end
  
  def show
  end
  
  def edit
  end
  
  def update
    if @user.update(user_params)
      flash[:success] = "Your account was successfully updated!"
      redirect_to @user
    else
      render 'edit'
    end
  end
  
  def destroy
    @user.destroy
    flash[:danger] = "User and associated scenes have been deleted!"
    redirect_to users_path
  end
  
  private
  
  def require_same_user
    if current_user != @user
      flash[:notice] = "You can only edit or delete your own account"
      redirect_to users_path
    end
  end
  
  def set_user
    @user = User.find(params[:id])
  end
  
  def user_params
    params.require(:user). permit(:username, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_messages.html.erb
<div class="row">
  <div class="col-md-10 col-md-offset-3">
    <% flash.each do |name, msg| %>
      <div>
        <a href="#" class="close" data-dismiss="alert">&#215;</a>
        <%= msg %>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/_navbar.html.erb
    <!-- Fixed navbar -->
    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to "MyWebsite", root_path, class: "navbar-brand", id: "logo" %>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "Videos", scenes_path %></li>
            <li><a href="#">Stars</a></li>
            <li><a href="#about">About</a></li>
            <li><a href="#contact">Contact</a></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <% if logged_in? %>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                  <%= current_user.username.capitalize %>
                <span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <li><%= link_to "Profile", user_path(current_user) %></li>
                  <li><a href="#">Another action</a></li>
                  <li><a href="#">Something else here</a></li>
                  <li role="separator" class="divider"></li>
                  <li class="dropdown-header">Nav header</li>
                  <li><a href="#">Separated link</a></li>
                  <li><%= link_to 'Logout', logout_path, method: :delete %></li>
                </ul>
              </li>
            <% else %>
            <li><%= link_to 'Sign Up', signup_path %> <span class="sr-only">(current)</span></a></li>
            <li><%= link_to 'Log In', login_path %> <span class="sr-only">(current)</span></a></li>
            <% end %>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

app/views/layouts/_sidenav.html.erb
<div class="nav-side-menu">
    <div class="brand">Brand Logo</div>
    <i class="fa fa-bars fa-2x toggle-btn" data-toggle="collapse" data-target="#menu-content"></i>
    <div class="menu-list">
        <ul id="menu-content" class="menu-content collapse out">
            <li>
                <a href="#">
                    <i class="fa fa-dashboard fa-lg"></i> Dashboard
                </a>
            </li>
            <li data-toggle="collapse" data-target="#products" class="collapsed active">
                <a href="#"><i class="fa fa-gift fa-lg"></i> Scenes <span class="arrow"></span></a>
            </li>
            <ul class="sub-menu collapse" id="products">
                <li class="active"><a href="#">New Scene</a></li>
                <li><a href="#">Scenes Listing</a></li>
            </ul>
            <li data-toggle="collapse" data-target="#service" class="collapsed">
                <a href="#"><i class="fa fa-globe fa-lg"></i> Pornstars <span class="arrow"></span></a>
            </li>
            <ul class="sub-menu collapse" id="service">
                <li>New Service 1</li>
                <li>New Service 2</li>
                <li>New Service 3</li>
            </ul>


            <li data-toggle="collapse" data-target="#new" class="collapsed">
                <a href="#"><i class="fa fa-car fa-lg"></i> Categories <span class="arrow"></span></a>
            </li>
            <ul class="sub-menu collapse" id="new">
                <li>New New 1</li>
                <li>New New 2</li>
                <li>New New 3</li>
            </ul>
            <li>
                <a href="#">
                    <i class="fa fa-user fa-lg"></i> Profile
                </a>
            </li>
            <li>
                <a href="#">
                    <i class="fa fa-users fa-lg"></i> Users
                </a>
            </li>
        </ul>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyWebsite</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <%= render 'layouts/messages' %>
    <%= yield %>
  </body>
</html>

app/views/pages/dashboard.html.erb
  <%= render 'layouts/sidenav' %>
  <div class="container" id="main">  
      <div class="row">
        <div class="col-md-12">
          <h1 class="page-header">Dashboard</h1>

          <div class="row placeholders">
            <div class="col-xs-6 col-sm-3 placeholder">
              <img src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" width="200" height="200" class="img-responsive" alt="Generic placeholder thumbnail">
              <h4>Label</h4>
              <span class="text-muted">Something else</span>
            </div>
            <div class="col-xs-6 col-sm-3 placeholder">
              <img src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" width="200" height="200" class="img-responsive" alt="Generic placeholder thumbnail">
              <h4>Label</h4>
              <span class="text-muted">Something else</span>
            </div>
            <div class="col-xs-6 col-sm-3 placeholder">
              <img src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" width="200" height="200" class="img-responsive" alt="Generic placeholder thumbnail">
              <h4>Label</h4>
              <span class="text-muted">Something else</span>
            </div>
            <div class="col-xs-6 col-sm-3 placeholder">
              <img src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" width="200" height="200" class="img-responsive" alt="Generic placeholder thumbnail">
              <h4>Label</h4>
              <span class="text-muted">Something else</span>
            </div>
          </div>

          <h2 class="sub-header">Section title</h2>
          <div class="table-responsive">
            <table class="table table-striped">
              <thead>
                <tr>
                  <th>#</th>
                  <th>Header</th>
                  <th>Header</th>
                  <th>Header</th>
                  <th>Header</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td>1,001</td>
                  <td>Lorem</td>
                  <td>ipsum</td>
                  <td>dolor</td>
                  <td>sit</td>
                </tr>
                <tr>
                  <td>1,002</td>
                  <td>amet</td>
                  <td>consectetur</td>
                  <td>adipiscing</td>
                  <td>elit</td>
                </tr>
                <tr>
                  <td>1,003</td>
                  <td>Integer</td>
                  <td>nec</td>
                  <td>odio</td>
                  <td>Praesent</td>
                </tr>
                <tr>
                  <td>1,003</td>
                  <td>libero</td>
                  <td>Sed</td>
                  <td>cursus</td>
                  <td>ante</td>
                </tr>
                <tr>
                  <td>1,004</td>
                  <td>dapibus</td>
                  <td>diam</td>
                  <td>Sed</td>
                  <td>nisi</td>
                </tr>
                <tr>
                  <td>1,005</td>
                  <td>Nulla</td>
                  <td>quis</td>
                  <td>sem</td>
                  <td>at</td>
                </tr>
                <tr>
                  <td>1,006</td>
                  <td>nibh</td>
                  <td>elementum</td>
                  <td>imperdiet</td>
                  <td>Duis</td>
                </tr>
                <tr>
                  <td>1,007</td>
                  <td>sagittis</td>
                  <td>ipsum</td>
                  <td>Praesent</td>
                  <td>mauris</td>
                </tr>
                <tr>
                  <td>1,008</td>
                  <td>Fusce</td>
                  <td>nec</td>
                  <td>tellus</td>
                  <td>sed</td>
                </tr>
                <tr>
                  <td>1,009</td>
                  <td>augue</td>
                  <td>semper</td>
                  <td>porta</td>
                  <td>Mauris</td>
                </tr>
                <tr>
                  <td>1,010</td>
                  <td>massa</td>
                  <td>Vestibulum</td>
                  <td>lacinia</td>
                  <td>arcu</td>
                </tr>
                <tr>
                  <td>1,011</td>
                  <td>eget</td>
                  <td>nulla</td>
                  <td>Class</td>
                  <td>aptent</td>
                </tr>
                <tr>
                  <td>1,012</td>
                  <td>taciti</td>
                  <td>sociosqu</td>
                  <td>ad</td>
                  <td>litora</td>
                </tr>
                <tr>
                  <td>1,013</td>
                  <td>torquent</td>
                  <td>per</td>
                  <td>conubia</td>
                  <td>nostra</td>
                </tr>
                <tr>
                  <td>1,014</td>
                  <td>per</td>
                  <td>inceptos</td>
                  <td>himenaeos</td>
                  <td>Curabitur</td>
                </tr>
                <tr>
                  <td>1,015</td>
                  <td>sodales</td>
                  <td>ligula</td>
                  <td>in</td>
                  <td>libero</td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>
      </div>
  </div>  

app/views/pages/home.html.erb
    <div class="container">

      <!-- Main component for a primary marketing message or call to action -->
      <div class="jumbotron">
        <h1>Navbar example</h1>
        <p>This example is a quick exercise to illustrate how the default, static and fixed to top navbar work. It includes the responsive CSS and HTML, so it also adapts to your viewport and device.</p>
        <p>To see the difference between static and fixed top navbars, just scroll.</p>
        <p align="center">
          <%= link_to 'Sign Up', signup_path, class: 'btn btn-lg' %>
        </p>
      </div>

    <div class="row">
  <div class="col-lg-4">
    <h2>Heading</h2>
    <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
    <p><a class="btn btn-primary btn-xlarge" href="#" role="button">View details »</a></p>
  </div>
  <div class="col-lg-4">
    <h2>Heading</h2>
    <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
    <p><a class="btn btn-primary btn-xlarge" href="#" role="button">View details »</a></p>
 </div>
  <div class="col-lg-4">
    <h2>Heading</h2>
    <p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa.</p>
    <p><a class="btn btn-primary btn-xlarge" href="#" role="button">View details »</a></p>
  </div>
</div>

    </div> <!-- /container -->
    


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script>
    <script src="../../dist/js/bootstrap.min.js"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="../../assets/js/ie10-viewport-bug-workaround.js"></script>

app/views/scenes/_scene.html.erb
<% obj.each do |scene| %>
  <div class="row">
    <div class="col-md-2">
      <section class="center">
        
      </section>
    </div>
    <div class="col-md-8 well">
      <h4><%= link_to scene.title, scene_path(scene) %></h4>
      <p><%= truncate(scene.description, length: 150) %></p>
      <p>
        <span class="quiet"><small>Created <%= time_ago_in_words(scene.created_at) %> ago</small></span>
      </p>
    </div>
  </div>
<% end %>

app/views/scenes/edit.html.erb
<%= render 'layouts/sidenav' %>
<% if @scene.errors.any? %>
  <div class="row">
    <div class="col-md-6 col-md-offset-4">
      <div class="panel">
        <h2 class="panel-title">
          <%= pluralize(@scene.errors.count, "error") %> 
          prohibited this <%= @scene.class %> from being saved.
        </h2>
        <div class="panel-body">
            <ul>
              <%= @scene.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
              <% end %>
            </ul>
        </div>
      </div>
    </div>
  </div>
<% end %>

<div class= "row">
  <div class="col-md-10 col-md-offset-2">
    <%= form_for(@scene, :html => {class: "form-horizontal", role: "form"}) do |scene| %>
      <div class="form-group">
        <div class="control-label col-md-2">
          <%= scene.label :title %>
        </div>
        <div class="col-md-8">
          <%= scene.text_field :title, class: "form-control", placeholder: "Title of the scene", autofocus: true %>
        </div>
      </div>
      <div class="form-group">
        <div class="control-label col-md-2">
          <%= scene.label :description %>
        </div>
        <div class="col-md-8">
          <%= scene.text_area :description, rows: 10, class: "form-control", placeholder: "Scene description" %>
        </div>
      </div>
      <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
          <%= scene.submit class: "btn btn-primary btn-lg btn-xlarge" %>
        </div>
      </div>
    <% end %>
    <div class="col-md-4 col-md-offset-4">
      [ <%= link_to "Cancel request and return to scenes listing", scenes_path %> ]
    </div>
  </div>
</div>

  

app/views/scenes/index.html.erb
<h1 align = "center">Scenes Listing</h1>
<hr />

<%= render 'scene', obj: @scenes %>
<div align="center"><%= will_paginate %></div>

app/views/scenes/listing.html.erb
  <%= render 'layouts/sidenav' %>
  <div class="container" id="main">  
      <div class="row">
        <div class="col-md-12">
          <h1 class="page-header">Scenes Listing</h1>

          <div class="row placeholders">
            <div class="col-xs-6 col-md-3 placeholder">
              <img src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" width="200" height="200" class="img-responsive" alt="Generic placeholder thumbnail">
              <h4>Label</h4>
              <span class="text-muted">Something else</span>
            </div>
            <div class="col-xs-6 col-md-3 placeholder">
              <img src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" width="200" height="200" class="img-responsive" alt="Generic placeholder thumbnail">
              <h4>Label</h4>
              <span class="text-muted">Something else</span>
            </div>
            <div class="col-xs-6 col-md-3 placeholder">
              <img src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" width="200" height="200" class="img-responsive" alt="Generic placeholder thumbnail">
              <h4>Label</h4>
              <span class="text-muted">Something else</span>
            </div>
            <div class="col-xs-6 col-md-3 placeholder">
              <img src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" width="200" height="200" class="img-responsive" alt="Generic placeholder thumbnail">
              <h4>Label</h4>
              <span class="text-muted">Something else</span>
            </div>
          </div>

          <h2 class="sub-header">Scenes List</h2>
          <div class="table-responsive">
            <table class="table table-striped">
              <thead>
                <tr>
                  <th>Scene ID</th>
                  <th>Title</th>
                  <th>Edit</th>
                  <th>Delete</th>
                </tr>
              </thead>
              <tbody>
                <% @scenes.each do |scene| %>
                  <tr>
                    <td><%= scene.id %></td>
                    <td><%= link_to scene.title, scene_path(scene) %></td>
                    <td><%= link_to "Edit", edit_scene_path(scene) %></td>
                    <td><%= link_to "Delete", scene_path(scene), method: :delete,
                                              data: { confirm: "Are you sure you want to delete this scene?" } %></td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          </div>
        </div>
      </div>
  </div>  

app/views/scenes/new.html.erb
<%= render 'layouts/sidenav' %>
<% if @scene.errors.any? %>
  <div class="row">
    <div class="col-md-6 col-md-offset-4">
      <div class="panel">
        <h2 class="panel-title">
          <%= pluralize(@scene.errors.count, "error") %> 
          prohibited this <%= @scene.class %> from being saved.
        </h2>
        <div class="panel-body">
            <ul>
              <%= @scene.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
              <% end %>
            </ul>
        </div>
      </div>
    </div>
  </div>
<% end %>

<div class= "row">
  <div class="col-md-10 col-md-offset-2">
    <%= form_for(@scene, :html => {class: "form-horizontal", role: "form"}) do |scene| %>
      <div class="form-group">
        <div class="control-label col-md-2">
          <%= scene.label :title %>
        </div>
        <div class="col-md-8">
          <%= scene.text_field :title, class: "form-control", placeholder: "Title of the scene", autofocus: true %>
        </div>
      </div>
      <div class="form-group">
        <div class="control-label col-md-2">
          <%= scene.label :description %>
        </div>
        <div class="col-md-8">
          <%= scene.text_area :description, rows: 10, class: "form-control", placeholder: "Scene description" %>
        </div>
      </div>
      <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
          <%= scene.submit class: "btn btn-primary btn-lg btn-xlarge" %>
        </div>
      </div>
    <% end %>
    <div class="col-md-4 col-md-offset-4">
      [ <%= link_to "Cancel request and return to scenes listing", scenes_path %> ]
    </div>
  </div>
</div>

  

app/views/scenes/show.html.erb
<h1 align="center"><%= @scene.title.capitalize %></h1>
<div class="well col-md-8 col-md-offset-2"
<p><%= simple_format(@scene.description) %></p>
<span class="quiet"><small>Created <%= time_ago_in_words(@scene.created_at) %> ago</small></span>

app/views/users/_form.html.erb
<div class= "row">
  <div class="col-md-12">
    <%= form_for(@user, :html => {class: "form-horizontal", role: "form"}) do |user| %>
      <div class="form-group">
        <div class="control-label col-md-2">
          <%= user.label :username %>
        </div>
        <div class="col-md-8">
          <%= user.text_field :username, class: "form-control", placeholder: "Type your username", autofocus: true %>
        </div>
      </div>
      <div class="form-group">
        <div class="control-label col-md-2">
          <%= user.label :email %>
        </div>
        <div class="col-md-8">
          <%= user.email_field :email, class: "form-control", placeholder: "Enter your email" %>
        </div>
      </div>
      <div class="form-group">
        <div class="control-label col-md-2">
          <%= user.label :password %>
        </div>
        <div class="col-md-8">
          <%= user.password_field :password, class: "form-control", placeholder: "Choose a password" %>
        </div>
      </div>
      <div class="form-group">
        <div class="control-label col-md-2">
          <%= user.label :password_confirmation, "Confirm password" %>
        </div>
        <div class="col-md-8">
          <%= user.password_field :password_confirmation, class: "form-control", placeholder: "Confirm your password" %>
        </div>
      </div>
      <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
          <%= user.submit(@user.new_record? ? "Sign Up" : "Update", class: "btn btn-primary btn-lg btn-xlarge") %>
        </div>
      </div>
    <% end %>
    <div class="col-md-4 col-md-offset-4">
      [ <%= link_to "Cancel request and return to scenes listing", scenes_path %> ]
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<% if @user.errors.any? %>
  <div class="row">
    <div class="col-md-6 col-md-offset-4">
      <div class="panel">
        <h2 class="panel-title">
          <%= pluralize(@user.errors.count, "error") %> 
          prohibited this <%= @user.class %> from being saved.
        </h2>
        <div class="panel-body">
            <ul>
              <% @user.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
              <% end %>
            </ul>
        </div>
      </div>
    </div>
  </div>
<% end %>

<h1 align = "center">Edit Your Profile</h1>
</br>

<%= render 'form' %>

app/views/users/index.html.erb
<h1 align="center">Users List</h1>

<% @users.each do |user| %>
  <div class="row">
    <div class="col-md-2">
      <section class="center">
        
      </section>
    </div>
    <div class="col-md-8 well">
      <h4><%= link_to user.username, user_path(user) %></h4>
      <p>
        <span class="quiet"><small>Registered <%= time_ago_in_words(user.created_at) %> ago</small></span>
        <li><%= link_to 'Delete this user', user_path(user), method: :delete, 
                  data: { confirm: "Are you sure you want to delete this user and all associated scenes?" } %></li>
      </p>
    </div>
  </div>
  <%= will_paginate %>
<% end %>

app/views/users/show.html.erb
<h1 align="center"><%= "#{@user.username.capitalize}'s profile" %></h1>
  
<div class="row">
  <div class="col-md-4 col-md-offset-4 center">
    <p align = "center">Avatar</p>
    <div class="col-md-4 col-md-offset-4">
      [ <%= link_to "Edit your profile", edit_user_path %> ]
    </div>
  </div>
</div>